spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/imagebase
    username: imagebase
    password: ImageBase2023Run
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 60000